
from sqlalchemy import Column, Integer, String, ForeignKey, Numeric, DateTime
from sqlalchemy.orm import relationship
import datetime
from sqlalchemy.types import Date
from pnboia_api.db.base import Base

class DataBuoy(Base):
    __tablename__ = "data_buoys"

    id = Column(Integer, primary_key=True, index=True )
    lat = Column(Numeric(9,6))
    lon = Column(Numeric(9,6))
    date_time = Column(DateTime)
    battery = Column(Numeric(10,2))
    compass = Column(Integer)
    flag_compass = Column(Integer)
    flood = Column(Integer)
    rh = Column(Numeric(10,2))
    flag_rh = Column(Integer)
    pres = Column(Numeric(10,1))
    flag_pres = Column(Integer)
    atmp = Column(Numeric(10,2))
    flag_atmp = Column(Integer)
    dewpt = Column(Numeric(10,2))
    flag_dewpt = Column(Integer)
    wspd = Column(Numeric(10,2))
    flag_wspd = Column(Integer)
    wdir = Column(Integer)
    flag_wdir = Column(Integer)
    gust = Column(Numeric(10,2))
    flag_gust = Column(Integer)
    arad = Column(Numeric(10,2))
    flag_arad = Column(Integer)
    sst = Column(Numeric(10,2))
    flag_sst = Column(Integer)
    cspd1 = Column(Numeric(10,2))
    flag_cspd1 = Column(Integer)
    cdir1 = Column(Integer)
    flag_cdir1 = Column(Integer)
    cspd2 = Column(Numeric(10,2))
    flag_cspd2 = Column(Integer)
    cdir2 = Column(Integer)
    flag_cdir2 = Column(Integer)
    cspd3 = Column(Numeric(10,2))
    flag_cspd3 = Column(Integer)
    cdir3 = Column(Integer)
    flag_cdir3 = Column(Integer)
    swvht1 = Column(Numeric(10,2))
    flag_swvht1 = Column(Integer)
    swvht2 = Column(Numeric(16,2))
    flag_swvht2 = Column(Integer)
    mxwvht1 = Column(Numeric(10,2))
    flag_mxwvht1 = Column(Integer)
    tp1 = Column(Numeric(10,1))
    flag_tp1 = Column(Integer)
    tp2 = Column(Numeric(10,1))
    flag_tp2 = Column(Integer)
    wvdir1 = Column(Integer)
    flag_wvdir1 = Column(Integer)
    wvdir2 = Column(Integer)
    flag_wvdir2 = Column(Integer)
    wvspread1 = Column(Integer)
    flag_wvspread1 = Column(Integer)
    pk_dir = Column(Integer)
    flag_pk_dir = Column(Integer)
    pk_wvspread = Column(Integer)
    flag_pk_wvspread = Column(Integer)
    mean_tp = Column(Numeric(10,1))
    flag_mean_tp = Column(Integer)
    buoy_id = Column(Integer, ForeignKey("buoys.id"), nullable=False)
    buoy = relationship("Buoy", back_populates="data_buoys")
